In [1]:
import pandas as pd

In [2]:
import numpy as np

In [15]:
import sklearn as sk
from  sklearn.svm import SVC

In [7]:
data = pd.read_csv('svm-data.csv', header = None)

In [8]:
data.head()

0     1     2
0  0  0.70  0.29
1  1  0.23  0.55
2  0  0.72  0.42
3  0  0.98  0.68
4  0  0.48  0.39

In [9]:
X = data.as_matrix(columns = [1, 2])

In [13]:
y = data.as_matrix(columns = [0]).ravel()

In [14]:
y

array([ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.])

In [17]:
clf = SVC(C = 100000, kernel = 'linear', random_state = 241)

In [18]:
clf.fit(X, y)

SVC(C=100000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=241, shrinking=True,
  tol=0.001, verbose=False)

In [19]:
support_vectors = clf.support_

In [20]:
support_vectors

array([3, 4, 9], dtype=int32)

In [21]:
# Answer

In [22]:
support_vectors + 1

array([ 4,  5, 10], dtype=int32)